import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"></link>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  

      <main className="container mt-5">
      <div className="d-flex flex-wrap" >
    <Image
         src="/trendingAsset.PNG"
        width={30}
        height={24}
        priority
            />
Trending Assets
</div>
<div className='row mt-5'>
  <div className='col-12'>
  <div className="d-flex justify-content-around">

<div className='mt-5'>
<div className={styles.circle}>
<div className={styles.nestedCircle}>
<Image
         src="/bitcoin.PNG"
        width={30}
        height={30}
        className={styles.img}
        priority
            />
</div>


</div>
<div className={styles.circleRight}></div>
<div className={styles.circleLeft}></div>
<div className={styles.box}>
<div class="d-flex justify-content-center mt-4">
  <span className={styles.currency}>Bitcoin(BTC)</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$31812.234 <span class='text-success'>+10%</span></p>
  </span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.currency}>Price</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$600000</p>
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>TVL</span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.tvl}>
  <Image
         src="/tvl.PNG"
        width={90}
        height={20}
        className={styles.tvlImg}
        priority
            />
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>Popular pairs</span>
</div>
</div>
</div>

<div  className='mt-5'>
<div className={styles.circle}>
<div className={styles.nestedCircle}>
<Image
         src="/bitcoin.PNG"
        width={30}
        height={30}
        className={styles.img}
        priority
            />
</div>
</div>
<div className={styles.circleRight}></div>
<div className={styles.circleLeft}></div>
<div className={styles.box}>
<div class="d-flex justify-content-center mt-4">
  <span className={styles.currency}>Solana(SQL)</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$31812.234 <span class='text-success'>+10%</span></p>
  </span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.currency}>Price</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$600000</p>
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>TVL</span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.tvl}>
  <Image
         src="/tvl.PNG"
        width={90}
        height={20}
        className={styles.tvlImg}
        priority
            />
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>Popular pairs</span>
</div>

</div>
</div>
<div className='mt-5'>
<div className={styles.circle}>
<div className={styles.nestedCircle}>
<Image
         src="/bitcoin.PNG"
        width={30}
        height={30}
        className={styles.img}
        priority
            />
</div>

</div>
<div className={styles.circleRight}></div>
<div className={styles.circleLeft}></div>
<div className={styles.box}>
<div class="d-flex justify-content-center mt-4">
  <span className={styles.currency}>Etherem (ETH)</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$31812.234 <span class='text-success'>+10%</span></p>
  </span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.currency}>Price</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$600000</p>
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>TVL</span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.tvl}>
  <Image
         src="/tvl.PNG"
        width={90}
        height={20}
        className={styles.tvlImg}
        priority
            />
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>Popular pairs</span>
</div>

</div>
</div>
<div className='mt-5'>
<div className={styles.circle}>
<div className={styles.nestedCircle}>
<Image
         src="/bitcoin.PNG"
        width={30}
        height={30}
        className={styles.img}
        priority
            />
</div>
</div>
<div className={styles.circleRight}></div>
<div className={styles.circleLeft}></div>
<div className={styles.box}>
<div class="d-flex justify-content-center mt-4">
  <span className={styles.currency}>Bitcoin(BTC)</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$232.234 <span class='text-danger'>+10%</span></p>
  </span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.currency}>Price</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$2000</p>
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>TVL</span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.tvl}>
  <Image
         src="/tvl.PNG"
        width={90}
        height={20}
        className={styles.tvlImg}
        priority
            />
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>Popular pairs</span>
</div>

</div>
</div>
<div className='mt-5'>
<div className={styles.circle}>
<div className={styles.nestedCircle}>
<Image
         src="/bitcoin.PNG"
        width={30}
        height={30}
        className={styles.img}
        priority
            />
</div>
</div>
<div className={styles.circleRight}></div>
<div className={styles.circleLeft}></div>
<div className={styles.box}>
<div class="d-flex justify-content-center mt-4">
  <span className={styles.currency}>Bitcoin(BTC)</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$31812.234 <span class='text-success'>+10%</span></p>
  </span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.currency}>Price</span>
</div>
<div class="d-flex justify-content-center mt-2">
  <span className={styles.input}>
  <p class="text-center">$600000</p>
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>TVL</span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.tvl}>
  <Image
         src="/tvl.PNG"
        width={90}
        height={20}
        className={styles.tvlImg}
        priority
            />
  </span>
</div>
<div class="d-flex justify-content-center mt-1">
  <span className={styles.currency}>Popular pairs</span>
</div>

</div>
</div>


</div>

  </div>

</div>



       
      </main>
    </>
  )
}
